name: macOS Experimental Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [macos-latest]
        qt: [qt5]
    runs-on:  ${{ matrix.os }}
    name: ${{ matrix.os }} ${{ matrix.qt }}
    timeout-minutes: 60
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install Homebrew packages
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1
      run: |
        export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
        ./scripts/macosx-build-homebrew.sh ${{ matrix.qt }}
    - name: Build OpenSCAD
      run: |
        env
        mkdir build
        cd build
        cmake .. --debug-find -DCMAKE_BUILD_TYPE=Release -DCMAKE_UNITY_BUILD=ON -DEXPERIMENTAL=ON -DSNAPSHOT=ON $CMAKE_OPTIONS
        export NUMCPU=$(($(sysctl -n hw.ncpu) * 3 / 2))
        make -j$NUMCPU
        ls build
    - name: Upload
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: MacOS ${{ matrix.qt }}
        path: |
          build/ctest
